// Built-in content for activities. Work-safe by design.

import type { ActivityType } from './types'

export interface ActivityPlayerGuide {
  /** Shown on the activity card, e.g. "4–12 players". */
  label: string
  /** Recommended range; null upper bound means "the more the merrier". */
  best: [number, number | null]
  /** Shown when the room exceeds the recommended maximum. */
  tooManyNote?: string
}

export const ACTIVITY_PLAYER_GUIDE: Record<ActivityType, ActivityPlayerGuide> = {
  icebreaker: { label: '2+ players', best: [2, null] },
  'this-or-that': { label: '2+ players', best: [2, null] },
  'two-truths': {
    label: '3–8 players',
    best: [3, 8],
    tooManyNote: 'One turn per person — long with a big group. Consider a few volunteers instead.',
  },
  snowfight: {
    label: '4–12 players',
    best: [4, 12],
    tooManyNote: 'The arena gets crowded above 12 — still playable, expect chaos.',
  },
  'how-many': { label: '4+ players', best: [4, null] },
  'whose-fact': { label: '4+ players', best: [4, null] },
  herd: { label: '4+ players', best: [4, null] },
  caption: { label: '4+ players', best: [4, null] },
  undercover: {
    label: '4–12 players',
    best: [4, 12],
    tooManyNote: 'Discussion gets chaotic above 12 — still works, keep clue rounds short.',
  },
  wavelength: {
    label: '3–10 players',
    best: [3, 10],
    tooManyNote: 'One clue-giver turn per person — long above 10. End early anytime.',
  },
  territory: { label: '4–20 players', best: [4, 20] },
}

export const ICEBREAKER_QUESTIONS: string[] = [
  'What was your very first job?',
  'What is a skill you would love to master overnight?',
  'What is the best concert or live event you have ever attended?',
  'If you could live in any city for a year, which one would you pick?',
  'What is your go-to comfort food?',
  'What was your first computer or gaming console?',
  'What is a movie you can rewatch endlessly?',
  'What is the most beautiful place you have ever visited?',
  'If you were not in tech, what job would you have?',
  'What is a small thing that instantly improves your day?',
  'What hobby have you always wanted to try?',
  'What is the strangest food combination you genuinely enjoy?',
  'What was your favourite childhood cartoon or TV show?',
  'If you could have dinner with any historical figure, who would it be?',
  'What is the best piece of advice you have ever received?',
  'What is your most useless talent?',
  'If animals could talk, which species would be the rudest?',
  'What is a book you would recommend to anyone?',
  'What is your favourite way to spend a rainy Sunday?',
  'If you won the lottery tomorrow, what is the first thing you would do?',
  'What is the worst fashion choice you ever made?',
  'What song always gets you moving?',
  'What is something you learned recently that surprised you?',
  'If you could teleport anywhere right now for one hour, where would you go?',
  'What was your favourite subject in school?',
  'What is the best gift you have ever received?',
  'Which fictional world would you most like to live in?',
  'What is your guilty pleasure TV show?',
  'If you had to eat one meal every day for the rest of your life, what would it be?',
  'What is the most spontaneous thing you have ever done?',
  'What did you want to be when you were 10 years old?',
  'What is one thing on your bucket list?',
  'Mountains, beach, or city trip?',
  'What is the funniest thing that happened to you at work?',
  'If you could instantly speak another language, which would you choose?',
  'What app on your phone do you use the most (be honest)?',
  'What is your favourite board game or card game?',
  'What is the best meal you have ever cooked yourself?',
  'If your life had a theme song, what would it be?',
  'What is one thing your teammates would be surprised to learn about you?',
]

export const HOW_MANY_QUESTIONS: string[] = [
  'How many of us have broken a bone?',
  'How many of us have lived in another country?',
  'How many of us speak three or more languages?',
  'How many of us have met a celebrity?',
  'How many of us have been on TV or radio?',
  'How many of us can juggle?',
  'How many of us play a musical instrument?',
  'How many of us have run 10 km or more in one go?',
  'How many of us have a pet at home?',
  'How many of us have slept in a tent in the last year?',
  'How many of us can solve a Rubik’s cube?',
  'How many of us have stood on a stage in front of 100+ people?',
  'How many of us like pineapple on pizza?',
  'How many of us sing in the shower?',
  'How many of us have won a trophy or medal?',
  'How many of us have been scuba diving or snorkelling?',
  'How many of us are afraid of spiders?',
  'How many of us can whistle with our fingers?',
  'How many of us have eaten insects on purpose?',
  'How many of us still remember our childhood phone number?',
  'How many of us have pulled an all-nighter playing video games?',
  'How many of us drink more than three coffees a day?',
  'How many of us have cried during an animated movie?',
  'How many of us have gotten a haircut we deeply regretted?',
]

export const HERD_PROMPTS: string[] = [
  'Name a breakfast food',
  'Name a pizza topping',
  'Name something you find in an office',
  'Name a famous scientist',
  'Name a superhero',
  'Name a board game',
  'Name a country in Europe',
  'Name something that is yellow',
  'Name a programming language',
  'Name a movie everyone has seen',
  'Name an animal you would find on a farm',
  'Name a thing people forget at home',
  'Name a karaoke classic',
  'Name a sport played with a ball',
  'Name something you do on a Sunday',
  'Name a famous painter',
  'Name an ice cream flavour',
  'Name a thing in the sky',
  'Name a household chore',
  'Name a city that never sleeps',
]

export const CAPTION_PROMPTS: string[] = [
  'Your out-of-office reply on the last day before a long vacation:',
  'The commit message at 4:59 pm on a Friday:',
  'What the office plant would say if it could talk:',
  'The subject line of the email nobody wants to open:',
  'A motivational poster for the Monday morning stand-up:',
  'The error message that should exist but does not:',
  'What your keyboard would complain about:',
  'The tagline for a movie about our team:',
  'A fortune cookie written for developers:',
  'The name of the ship that carries all our unfinished side projects:',
  'What the coffee machine thinks at 8:55 am:',
  'The warning label our meeting room should have:',
  'A slogan for the snooze button:',
  'What the 404 page should actually say:',
  'The autobiography title of your laptop:',
]

export const UNDERCOVER_WORD_PAIRS: { a: string; b: string }[] = [
  { a: 'Coffee', b: 'Tea' },
  { a: 'Beach', b: 'Swimming pool' },
  { a: 'Cat', b: 'Dog' },
  { a: 'Pizza', b: 'Burger' },
  { a: 'Cinema', b: 'Theatre' },
  { a: 'Bicycle', b: 'Motorbike' },
  { a: 'Winter', b: 'Autumn' },
  { a: 'Guitar', b: 'Violin' },
  { a: 'Email', b: 'Letter' },
  { a: 'Mountain', b: 'Hill' },
  { a: 'Butter', b: 'Margarine' },
  { a: 'Hotel', b: 'Hostel' },
  { a: 'Football', b: 'Rugby' },
  { a: 'Painter', b: 'Sculptor' },
  { a: 'Train', b: 'Tram' },
  { a: 'Soup', b: 'Stew' },
  { a: 'Moon', b: 'Sun' },
  { a: 'Novel', b: 'Comic book' },
  { a: 'Chess', b: 'Checkers' },
  { a: 'Juice', b: 'Smoothie' },
  { a: 'Sneakers', b: 'Sandals' },
  { a: 'Elevator', b: 'Escalator' },
  { a: 'Tent', b: 'Caravan' },
  { a: 'Pancake', b: 'Waffle' },
]

export const WAVELENGTH_SPECTRUMS: { left: string; right: string }[] = [
  { left: 'Underrated', right: 'Overrated' },
  { left: 'Terrible pizza topping', right: 'Amazing pizza topping' },
  { left: 'Useless superpower', right: 'World-changing superpower' },
  { left: 'Boring', right: 'Fascinating' },
  { left: 'Bad habit', right: 'Good habit' },
  { left: 'Cheap', right: 'Expensive' },
  { left: 'Guilty pleasure', right: 'Openly loved' },
  { left: 'Scary', right: 'Cute' },
  { left: 'Low effort', right: 'High effort' },
  { left: 'Weekday activity', right: 'Weekend activity' },
  { left: 'Introvert heaven', right: 'Extrovert heaven' },
  { left: 'Old technology', right: 'Futuristic technology' },
  { left: 'Unhealthy', right: 'Healthy' },
  { left: 'Quiet', right: 'Loud' },
  { left: 'Small talk topic', right: 'Deep conversation topic' },
  { left: 'Overpaid job', right: 'Underpaid job' },
  { left: 'Bad movie', right: 'Masterpiece' },
  { left: 'Dangerous', right: 'Safe' },
  { left: 'Forgettable', right: 'Unforgettable' },
  { left: 'Needs no skill', right: 'Needs years of practice' },
]

export const THIS_OR_THAT_PAIRS: { prompt: string; optionA: string; optionB: string }[] = [
  { prompt: 'The eternal debate', optionA: 'Tabs', optionB: 'Spaces' },
  { prompt: 'Editor theme', optionA: 'Dark mode', optionB: 'Light mode' },
  { prompt: 'Morning fuel', optionA: 'Coffee', optionB: 'Tea' },
  { prompt: 'Working hours', optionA: 'Early bird', optionB: 'Night owl' },
  { prompt: 'Where do you work best?', optionA: 'Office', optionB: 'Home' },
  { prompt: 'Debugging style', optionA: 'Debugger', optionB: 'Print statements' },
  { prompt: 'Weekend plans', optionA: 'Outdoors', optionB: 'Couch' },
  { prompt: 'Pizza controversy', optionA: 'Pineapple yes', optionB: 'Pineapple never' },
  { prompt: 'Music while coding', optionA: 'Music on', optionB: 'Silence' },
  { prompt: 'Meeting preference', optionA: 'Camera on', optionB: 'Camera off' },
  { prompt: 'Holiday style', optionA: 'Planned itinerary', optionB: 'Wing it' },
  { prompt: 'Breakfast take', optionA: 'Sweet', optionB: 'Savoury' },
  { prompt: 'Pet person', optionA: 'Dogs', optionB: 'Cats' },
  { prompt: 'Code review vibe', optionA: 'Nitpick everything', optionB: 'Approve and move on' },
  { prompt: 'New project', optionA: 'Greenfield', optionB: 'Refactor legacy' },
  { prompt: 'Superpower pick', optionA: 'Fly', optionB: 'Invisibility' },
  { prompt: 'Texting style', optionA: 'Voice message', optionB: 'Type it out' },
  { prompt: 'Season preference', optionA: 'Summer', optionB: 'Winter' },
  { prompt: 'Git style', optionA: 'Rebase', optionB: 'Merge' },
  { prompt: 'Lunch habit', optionA: 'Same place always', optionB: 'Something new' },
]
